<?php

return [

    'actions' => [
        'index' => 'Xem',
        'create' => 'Thêm',
        'edit' => 'Sửa',
        'destroy' => 'Xóa',
    ],
    'modules' => [

        'category_articles' => 'Nhóm bài viết',
        'articles' => 'Bài viết',
        'category_media' => 'Nhóm media',
        'media' => 'Media',
        'category_attributes' => 'Nhóm thuộc tính',
        'attributes' => 'Thuộc tính',
        'category_products' => 'Danh mục sản phẩm',
        'products' => 'Sản phẩm',
        'roles' => 'Nhóm thành viên',
        'users' => 'Thành viên',
        'tags' => 'Tags',
        'brands' => 'Hãng sản xuất',
        'coupons' => 'Mã giảm giá',
        'pages' => 'Page',
        'addresses' => 'Chi nhánh',
        'menus' => 'Menu',
        'orders' => 'Đơn hàng',
        'order_logs' => 'Lịch sử đơn hàng',
        'order_configs' => 'Cấu hình đơn hàng',
        'orders_payment' => 'Lịch sử thanh toán online',
        'ships' => 'Quản lý vận chuyển',
        'comments' => 'Comment',
        'customers' => 'Quản lý khách hàng',
        'customer_logs' => 'Quản lý khách hàng logs',
        'customer_socials' => 'Cấu hình đăng nhập',
        'contacts' => 'Quản lý liên hệ',
        'generals' => 'Cấu hình hệ thống',
        'slides' => 'Quản lý Banner & Slide',
        'files' => 'Ảnh - [Permission]',
        'websites' => 'Quản lý website',
        'taxes' => 'Cấu hình thuế',
        'suppliers' => 'Nhà cung cấp',
        'suppliers_categories' => 'Nhóm nhà cung cấp',
        'product_deals' => 'Sản phẩm mua kèm',
        'product_purchases' => 'Sản phẩm - Nhập hàng',
        'payment_vouchers' => 'Sổ quỹ - Phiếu chi',
        'receipt_vouchers' => 'Sổ quỹ - Phiếu thu',
        'quizzes' => 'Danh sách nguy cơ bệnh',
        'quiz_categories' => 'Nhóm đề thi',
        'questions' => 'Câu hỏi',
        'quiz_configs' => 'Cấu hình đề thi',
        'course_categories' => 'Danh mục khóa học',
        'courses' => 'Khóa học',
        'question_option_users' => 'Danh sách bài đã thi',
        'customer_levels' => 'Cấp bậc',
        'order_onlines' => 'Đặt thuốc online',
        'faqs' => 'Câu Hỏi Thường Gặp',
        'teams' => 'Đội Ngũ Bác Sỹ',
        'faculty_categories' => 'Nhóm các phòng, khóa',
        'faculties' => 'Danh sách các phòng khoa',
    ],
    'customer_levels' => [
        'index' => 'customer_levels_index',
    ],
    'order_onlines' => [
        'index' => 'order_onlines_index',
        'destroy' => 'order_onlines_destroy',
    ],
    'question_option_users' => [
        'index' => 'question_option_users_index',
        'edit' => 'question_option_users_edit',
    ],
    'customer_socials' => [
        'edit' => 'customer_socials_edit',
    ],
    'faculty_categories' => [
        'index' => 'faculty_categories_index',
        'create' => 'faculty_categories_create',
        'edit' => 'faculty_categories_edit',
        'destroy' => 'faculty_categories_destroy',
    ],
    'faculties' => [
        'index' => 'faculties_index',
        'create' => 'faculties_create',
        'edit' => 'faculties_edit',
        'destroy' => 'faculties_destroy',
    ],
    'teams' => [
        'index' => 'teams_index',
        'create' => 'teams_create',
        'edit' => 'teams_edit',
        'destroy' => 'teams_destroy',
    ],
    'faqs' => [
        'index' => 'faqs_index',
        'create' => 'faqs_create',
        'edit' => 'faqs_edit',
        'destroy' => 'faqs_destroy',
    ],
    'course_categories' => [
        'index' => 'course_categories_index',
        'create' => 'course_categories_create',
        'edit' => 'course_categories_edit',
        'destroy' => 'course_categories_destroy',
    ],
    'courses' => [
        'index' => 'courses_index',
        'create' => 'courses_create',
        'edit' => 'courses_edit',
        'destroy' => 'courses_destroy',
    ],
    'quiz_configs' => [
        'index' => 'quiz_configs_index',
        'create' => 'quiz_configs_create',
        'edit' => 'quiz_configs_edit',
        'destroy' => 'quiz_configs_destroy',
    ],
    'quiz_categories' => [
        'index' => 'quiz_categories_index',
        'create' => 'quiz_categories_create',
        'edit' => 'quiz_categories_edit',
        'destroy' => 'quiz_categories_destroy',
    ],
    'quizzes' => [
        'index' => 'quizzes_index',
        'create' => 'quizzes_create',
        'edit' => 'quizzes_edit',
        'destroy' => 'quizzes_destroy',
    ],
    'questions' => [
        'index' => 'questions_index',
        'create' => 'questions_create',
        'edit' => 'questions_edit',
        'destroy' => 'questions_destroy',
    ],
    'product_deals' => [
        'index' => 'product_deals_index',
        'create' => 'product_deals_create',
        'edit' => 'product_deals_edit',
        'destroy' => 'product_deals_destroy',
    ],
    'payment_vouchers' => [
        'index' => 'payment_vouchers_index',
        'create' => 'payment_vouchers_create',
        'edit' => 'payment_vouchers_edit',
        'destroy' => 'payment_vouchers_destroy',
    ],
    'receipt_vouchers' => [
        'index' => 'receipt_vouchers_index',
        'create' => 'receipt_vouchers_create',
        'edit' => 'receipt_vouchers_edit',
        'destroy' => 'receipt_vouchers_destroy',
    ],
    'product_purchases' => [
        'index' => 'product_purchases_index',
        'create' => 'product_purchases_create',
        'edit' => 'product_purchases_edit',
        'destroy' => 'product_purchases_destroy',
    ],
    'suppliers' => [
        'index' => 'suppliers_index',
        'create' => 'suppliers_create',
        'edit' => 'suppliers_edit',
        'destroy' => 'suppliers_destroy',
    ],
    'suppliers_categories' => [
        'index' => 'suppliers_categories_index',
        'create' => 'suppliers_categories_create',
        'edit' => 'suppliers_categories_edit',
        'destroy' => 'suppliers_categories_destroy',
    ],
    'websites' => [
        'index' => 'websites_index',
        'create' => 'websites_create',
        'edit' => 'websites_edit',
        'destroy' => 'websites_destroy',
    ],
    'taxes' => [
        'index' => 'taxes_index',
        'create' => 'taxes_create',
        'edit' => 'taxes_edit',
        'destroy' => 'taxes_destroy',
    ],
    'category_articles' => [
        'index' => 'category_articles_index',
        'create' => 'category_articles_create',
        'edit' => 'category_articles_edit',
        'destroy' => 'category_articles_destroy',
    ],
    'articles' => [
        'index' => 'articles_index',
        'create' => 'articles_create',
        'edit' => 'articles_edit',
        'destroy' => 'articles_destroy',
    ],
    'category_media' => [
        'index' => 'category_media_index',
        'create' => 'category_media_create',
        'edit' => 'category_media_edit',
        'destroy' => 'category_media_destroy',
    ],
    'media' => [
        'index' => 'media_index',
        'create' => 'media_create',
        'edit' => 'media_edit',
        'destroy' => 'media_destroy',
    ],
    'category_attributes' => [
        'index' => 'category_attributes_index',
        'create' => 'category_attributes_create',
        'edit' => 'category_attributes_edit',
        'destroy' => 'category_attributes_destroy',
    ],
    'attributes' => [
        'index' => 'attributes_index',
        'create' => 'attributes_create',
        'edit' => 'attributes_edit',
        'destroy' => 'attributes_destroy',
    ],
    'category_products' => [
        'index' => 'category_products_index',
        'create' => 'category_products_create',
        'edit' => 'category_products_edit',
        'destroy' => 'category_products_destroy',
    ],
    'products' => [
        'index' => 'products_index',
        'create' => 'products_create',
        'edit' => 'products_edit',
        'destroy' => 'products_destroy',
    ],
    'roles' => [
        'index' => 'roles_index',
        'create' => 'roles_create',
        'edit' => 'roles_edit',
        'destroy' => 'roles_destroy',
    ],
    'users' => [
        'index' => 'users_index',
        'create' => 'users_create',
        'edit' => 'users_edit',
        'destroy' => 'users_destroy',
    ],
    'tags' => [
        'index' => 'tags_index',
        'create' => 'tags_create',
        'edit' => 'tags_edit',
        'destroy' => 'tags_destroy',
    ],
    'brands' => [
        'index' => 'brands_index',
        'create' => 'brands_create',
        'edit' => 'brands_edit',
        'destroy' => 'brands_destroy',
    ],
    'coupons' => [
        'index' => 'coupons_index',
        'create' => 'coupons_create',
        'edit' => 'coupons_edit',
        'destroy' => 'coupons_destroy',
    ],
    'ships' => [
        'index' => 'ships_index',
        'create' => 'ships_create',
        'edit' => 'ships_edit',
        'destroy' => 'ships_destroy',
    ],
    'pages' => [
        'index' => 'pages_index',
        'create' => 'pages_create',
        'edit' => 'pages_edit',
        'destroy' => 'pages_destroy',
    ], 'addresses' => [
        'index' => 'addresses_index',
        'create' => 'addresses_create',
        'edit' => 'addresses_edit',
        'destroy' => 'addresses_destroy',
    ], 'menus' => [
        'index' => 'menus_index',
        'create' => 'menus_create',
        'edit' => 'menus_edit',
        'destroy' => 'menus_destroy',
    ], 'orders' => [
        'index' => 'orders_index',
        'create' => 'orders_create',
        'edit' => 'orders_edit',
        'destroy' => 'orders_destroy',
    ], 'comments' => [
        'index' => 'comments_index',
        'create' => 'comments_create',
        'edit' => 'comments_edit',
        'destroy' => 'comments_destroy',
    ], 'customers' => [
        'index' => 'customers_index',
        'create' => 'customers_create',
        'edit' => 'customers_edit',
        'destroy' => 'customers_destroy',
    ], 'customer_logs' => [
        'index' => 'customer_logs_index',
        'destroy' => 'customer_logs_destroy',
    ], 'contacts' => [
        'index' => 'contacts_index',
    ], 'generals' => [
        'index' => 'generals_index',
    ], 'slides' => [
        'index' => 'slides_index',
    ], 'order_logs' => [
        'index' => 'order_logs_index',
        'destroy' => 'order_logs_destroy',
    ], 'order_configs' => [
        'index' => 'order_configs_index',
    ], 'orders_payment' => [
        'index' => 'orders_payment_index',
    ]
];
